#!/usr/bin/python
import os
#import cgi
import sys
import xml.etree.ElementTree as ET
import traceback

def GetQueryDict():
  queryDict= {}
  if 'QUERY_STRING' not in os.environ.keys(): return queryDict
  for query in os.environ['QUERY_STRING'].split('&'):
    queryDict[query.split('=')[0]]=query.split('=')[1]
  return queryDict  

configFolder='projects/'
queryDict = GetQueryDict()

if 'name' in queryDict.keys():
  name=queryDict['name']
else:
  print "Status: 400 Bad Request"
  print
  print "Name missing from url"
  sys.exit(1)

if name == "":
  name="__defaults"

config=configFolder + name + '.xml'

root=ET.parse(config).getroot()
mapbounds=ET.parse('mapbounds.xml').getroot()
project=ET.parse('project.xml').getroot()

nameElement=ET.SubElement(project,'name')
nameElement.text=name

root.append(mapbounds)
for node in project:
  root[0].append(node)

print "Content-type: text/xml"
print "Status: 200 OK"
print

ET.dump(root)
